package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Car

global Query q

rule "Car within budget"
    when
        $c: Car(getPrice() <= q.getBudget())
    then
        $c.setScore(70);
end

rule "Car very close to budget"
    when
        $c: Car(getPrice() > q.getBudget(), getPrice() <= q.getBudget()*1.05)
    then
        $c.setScore(40);
end

rule "Car close to budget"
    when
        $c: Car(getPrice() > q.getBudget()*1.05, getPrice() <= q.getBudget()*1.1)
    then
        $c.setScore(20);
end
