package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Car

global Query q

rule "low cost and eco friendly - bonus"
    agenda-group "recommendation"
    salience 190
    when
        $c: Car(getScore().getCheapAndEco() == 0, getScore().getLowCost() > 0, getScore().getEnvironment() > 0)
    then
        modify($c){getScore().setCheapAndEco(10)}
end
