package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Car
import ftn.siit.sbnz.SBNZ.model.Car.Type

global Query q

rule "Smaller car for inexperienced drivers"
    agenda-group "recommendation"
    salience 94
    when
        $c: Car(getScore().getExperience() == 0, (getType() == Type.CONVERTIBLE || getType() == Type.COUPE || getType() == Type.HATCHBACK), q.getExperience() < 4)
    then
        modify($c){getScore().setExperience(25)}
end
