package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Query.Gear
import ftn.siit.sbnz.SBNZ.model.Car
import ftn.siit.sbnz.SBNZ.model.Car.Gear

global Query q

rule "Manual gearbox prefered"
    when
        $c: Car(getGear() == Car.Gear.MANUAL, q.getGear() == Query.Gear.MANUAL)
    then
        $c.setScore(10);
end

rule "Automatic gearbox prefered"
    when
        $c: Car(getGear() == Car.Gear.AUTOMATIC, q.getGear() == Query.Gear.AUTOMATIC)
    then
        $c.setScore(10);
end
