package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Car

global Query q

rule "Low fuel and cheap registration - low cost bonus"
    agenda-group "recommendation"
    salience 194
    when
        $c: Car(getScore().getLowCost() == 0, getScore().getFuel() > 0, getScore().getRegistration() > 0)
    then
        modify($c){getScore().setLowCost(15)}
end
