package sbnz.integracija;
dialect  "mvel"

import ftn.siit.sbnz.SBNZ.model.Query
import ftn.siit.sbnz.SBNZ.model.Query.Purpose
import ftn.siit.sbnz.SBNZ.model.Car
import ftn.siit.sbnz.SBNZ.model.Car.Type

global Query q

rule "Sport cars"
    agenda-group "recommendation"
    salience 84
    when
        $c: Car(getScore().getPurpose() == 0, (getType() == Type.COUPE || getType() == Type.CONVERTIBLE), q.getPurpose() == Purpose.SPORT)
    then
        modify($c){getScore().setPurpose(15)}
end

rule "Off-road cars"
    agenda-group "recommendation"
    salience 83
    when
        $c: Car(getScore().getPurpose() == 0, (getType() == Type.SUV || getType() == Type.PICKUP), q.getPurpose() == Purpose.OFFROAD)
    then
        modify($c){getScore().setPurpose(15)}
end

rule "Transport cars"
    agenda-group "recommendation"
    salience 82
    when
        $c: Car(getScore().getPurpose() == 0, (getType() == Type.PICKUP || getType() == Type.STATIONWAGON || getType() == Type.SUV), q.getPurpose() == Purpose.TRANSPORT)
    then
        modify($c){getScore().setPurpose(15)}
end